# :schema https://github.com/zakstucke/etcher/blob/v0.0.16/py_rust/src/config/schema.json

ignore_files = [".gitignore"]
exclude = []

[engine]
keep_trailing_newline = true
allow_undefined = false
custom_extensions = []

[context.static]

[context.env]

[context.cli]
PY_RUST_VERSION = {commands = ["./dev_scripts/pkg.sh ver_py_rust"]}
