site_name: "Zetch"
site_url: "https://zakstucke.github.io/zetch/"  # Trailing slash is recommended
repo_url: "https://github.com/zakstucke/zetch"

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  custom_dir: docs/overrides
  features:
    # These both seem to have a lot of problems now with the finished setup, easier to just disable:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    scheme: slate  # This is just dark mode:
    primary: custom
    accent: custom

plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - git-committers:
      repository: zakstucke/zetch
      branch: main
  - search
  - macros:
      module_name: doc_macros

  # https://mkdocstrings.github.io/recipes/?h=recip#automatic-code-reference-pages
  - gen-files:
      scripts:
        - docs/python_autodoc.py

  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true
            inherited_members: true

  - exclude:
      glob:
        # zetch files shouldn't be in the output:
        - "*.zetch.*"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home:
      - index.md
  - Code Reference:
      - Rust-backed Python Library: py_rust_ref/


  - Contributing:
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
  - LICENSE.md
