# :schema https://github.com/zakstucke/zetch/blob/v0.0.9/py_rust/src/config/schema.json

ignore_files = [".gitignore"]
exclude = []

[engine]
custom_extensions = []

[context.static]

[context.env]

[context.cli]
PY_RUST_VERSION = {commands = ["./dev_scripts/pkg.sh ver_py_rust"]}
