#:schema https://raw.githubusercontent.com/zakstucke/zetch/v0.0.16/py_rust/src/config/schema.json

ignore_files = [".gitignore"]

exclude = []

[engine]
custom_extensions = []

# Sync pkg versions in non templated files as a post task:
[[tasks.post]]
commands = ["./dev_scripts/pkg.sh update_versions"]

[context.static]
PY_RUST_VERSION = { value = "0.0.16" }

[context.env]
DEBUG = { default = true, coerce = "bool" }

[context.cli]
ROOT_DIR = { commands = ["pwd"] }