[profile.profiler]
inherits = "release"  # Adds on top of the default release profile
incremental = true
debug = true
strip = false

# Modifying the test runtime (from release is just so much faster)
[profile.test]
inherits = "release"  # Adds on top of the default release profile
