name: "Py-Rust Build"

# Originally derived from https://github.com/samuelcolvin/watchfiles/blob/main/.github/workflows/ci.yml

on:
    workflow_call:
        inputs:
            new-sha:
                required: true
                type: string

jobs:
    build:
        name: >
            build on ${{ matrix.platform || matrix.os }} (${{ matrix.target }} - ${{ matrix.manylinux || 'auto' }})

        strategy:
            fail-fast: true # Want release to cancel if any fail, so may as well fail fast to save some minutes
            matrix:
                # os: [ubuntu, macos, windows] # see desc below on windows disable reason
                os: [ubuntu, macos]
                target: [x86_64, aarch64]
                manylinux: [auto]
                include:
                    # Windows temporarily disabled - for some reason win aarch64 always fails with ld-link: error: could not open 'python311.lib': no such file or directory
                    # Re-enable and fix (might be fixed by updates automatically) when windows needed
                    # - os: windows
                    #   ls: dir
                    # - os: windows
                    #   ls: dir
                    #   target: i686
                    #   python-architecture: x86
                    # - os: windows
                    #   ls: dir
                    #   target: aarch64
                    - os: ubuntu
                      platform: linux
                      target: i686
                    - os: ubuntu
                      platform: linux
                      target: armv7
                    - os: ubuntu
                      platform: linux
                      target: ppc64le
                    - os: ubuntu
                      platform: linux
                      target: s390x
                    # musllinux
                    - os: ubuntu
                      platform: linux
                      target: x86_64
                      manylinux: musllinux_1_1
                    - os: ubuntu
                      platform: linux
                      target: aarch64
                      manylinux: musllinux_1_1

        runs-on: ${{ matrix.os }}-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ inputs.new-sha }}

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.12"
                  architecture: ${{ matrix.python-architecture || 'x64' }}

            - name: copy in README and LICENSE from root
              run: cp README.md py_rust/README.md && cp LICENSE.md py_rust/LICENSE.md

            - name: build sdist
              if: ${{ matrix.os == 'ubuntu' && matrix.target == 'x86_64' && matrix.manylinux == 'auto' }}
              uses: PyO3/maturin-action@v1
              with:
                  command: sdist
                  args: --manifest-path py_rust/Cargo.toml --out py_rust/dist

            - name: build wheels
              uses: PyO3/maturin-action@v1
              with:
                  target: ${{ matrix.target }}
                  manylinux: ${{ matrix.manylinux || 'auto' }}
                  args: --manifest-path py_rust/Cargo.toml --release --out py_rust/dist --interpreter '3.8 3.9 3.10 3.11 3.12'
                  rust-toolchain: stable
                  docker-options: -e CI

            - run: ${{ matrix.ls || 'ls -lh' }} py_rust/dist/

            - uses: actions/upload-artifact@v3
              with:
                  name: py_rust_build_files
                  path: py_rust/dist
